// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsQGHuozqLVeVvANE0XR3LLzO34yrawuQ',
    appId: '1:887433877091:web:a9dc7f230a44a856750a56',
    messagingSenderId: '887433877091',
    projectId: 'dgmarked-267c5',
    authDomain: 'dgmarked-267c5.firebaseapp.com',
    storageBucket: 'dgmarked-267c5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaNlxut5OGen3SbtSmRLnIoKGTtoBqUBg',
    appId: '1:887433877091:android:f627b575820e5d82750a56',
    messagingSenderId: '887433877091',
    projectId: 'dgmarked-267c5',
    storageBucket: 'dgmarked-267c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8Pr1YRkgm3AEYBXHGc041gD9Qr1T9njQ',
    appId: '1:887433877091:ios:65b61515f65bf998750a56',
    messagingSenderId: '887433877091',
    projectId: 'dgmarked-267c5',
    storageBucket: 'dgmarked-267c5.firebasestorage.app',
    iosBundleId: 'com.andreas.dgMarketplace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8Pr1YRkgm3AEYBXHGc041gD9Qr1T9njQ',
    appId: '1:887433877091:ios:0d5015566a10b00d750a56',
    messagingSenderId: '887433877091',
    projectId: 'dgmarked-267c5',
    storageBucket: 'dgmarked-267c5.firebasestorage.app',
    iosBundleId: 'com.example.dgMarketplace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsQGHuozqLVeVvANE0XR3LLzO34yrawuQ',
    appId: '1:887433877091:web:07a7394569f48401750a56',
    messagingSenderId: '887433877091',
    projectId: 'dgmarked-267c5',
    authDomain: 'dgmarked-267c5.firebaseapp.com',
    storageBucket: 'dgmarked-267c5.firebasestorage.app',
  );
}
